trigger:
- master

jobs:
- job: HostedVM
  displayName: 'Azure Hosted VM'
  pool:
    vmImage: 'Ubuntu-16.04'
  
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  
  steps:
  - bash: |
      sudo apt-get update && sudo apt install -y \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-ugly \
          libgirepository1.0-dev \
          gir1.2-gstreamer-1.0 \
          libcairo2-dev

    name: InstallPackage
    
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  
  - bash: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  
  - bash: |
      pip install pytest pytest-azurepipelines
      python -m pytest
    displayName: 'pytest'

- job: Ubuntu1804
  displayName: 'Ubuntu 18.04'
  pool: 'Ubuntu1804'
  steps:
  - bash: |
      python3 -m venv venv
    displayName: 'Preparing virtual environment'

  - bash: |
      source ./venv/bin/activate
      sudo apt-get update && sudo apt-get install -y libcairo2-dev
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - bash: |
      source ./venv/bin/activate
      pip install pytest pytest-azurepipelines
      python -m pytest
    displayName: 'pytest'
